// EyVay — product data (single source of truth)
window.EY_DATA = {
  user: {
    name: 'نیما زمانی',
    initial: 'ن',
    location: 'تهران، ولیعصر',
    wallet: 280000,
    savings: 3450000,
    since: 'مهر ۱۴۰۳',
    level: 'طلایی',
  },
  categories: [
    { k: 'all',     label: 'همه',     icon: 'sparkle' },
    { k: 'food',    label: 'غذا',     icon: 'flame', tone: 'saffron' },
    { k: 'fashion', label: 'پوشاک',   icon: 'bag',   tone: 'rose' },
    { k: 'beauty',  label: 'آرایشی',  icon: 'star',  tone: 'plum' },
    { k: 'books',   label: 'کتاب',    icon: 'ticket', tone: 'sage' },
    { k: 'home',    label: 'خانه',    icon: 'home',  tone: 'cream' },
  ],
  trending: ['پیتزا', 'آرایشگاه', 'گل طبیعی', 'قهوه دم‌دستی', 'کفش اسپرت', 'کتاب رمان', 'ماساژ'],
  deals: [
    {
      id: 'd1',
      title: 'بسته‌ی صبحانه‌ی کامل با نوشیدنی',
      store: 'کافه روزگار',
      cat: 'food',
      tone: 'saffron',
      price: 125000,
      old: 225000,
      percent: 45,
      rating: 4.8,
      ratingCount: 234,
      distance: 420,
      address: 'خیابان ولیعصر، کوچه‌ی مهرداد',
      desc: 'املت خانگی، نان تازه‌ی سنگک، پنیر لیقوان، گردوی محلی، عسل چهل‌گیاه و یک فنجان قهوه یا چای. تا ساعت ۱۱ صبح.',
      endsIn: '۰۱:۲۳:۴۵',
      hot: true,
    },
    {
      id: 'd2',
      title: 'سه جلد کتاب رمان معاصر',
      store: 'نشرِ چشمه',
      cat: 'books',
      tone: 'rose',
      price: 360000,
      old: 540000,
      percent: 33,
      rating: 4.7,
      ratingCount: 102,
      distance: 1200,
      address: 'کریمخان، رو‌به‌روی پارک ساعی',
      desc: 'انتخاب هفته‌ی سردبیر: سه رمان از نویسندگان جوان ایرانی، با جلد سخت و کاغذ بالک.',
      endsIn: '۱۸:۴۰:۰۲',
    },
    {
      id: 'd3',
      title: 'لباس بافت زنانه — برند تِرانه',
      store: 'فروشگاه ترانه',
      cat: 'fashion',
      tone: 'rose',
      price: 520000,
      old: 780000,
      percent: 33,
      rating: 4.5,
      ratingCount: 88,
      distance: 2400,
      address: 'فرشته، مرکز خرید الهیه',
      desc: 'پشمی نرم و گرم، بافت ایتالیایی، مناسب روزهای پاییزی.',
      endsIn: '۰۵:۱۲:۱۰',
    },
    {
      id: 'd4',
      title: 'ست ادکلن مردانه — کلاسیک',
      store: 'پرفیومری نُت',
      cat: 'beauty',
      tone: 'plum',
      price: 1450000,
      old: 2300000,
      percent: 37,
      rating: 4.9,
      ratingCount: 410,
      distance: 3100,
      address: 'جردن، برج نگین',
      desc: 'ترکیبی از چوب صندل، بِرگاموت و وانیل؛ ماندگاری بالا.',
      endsIn: '۱۱:۳۳:۰۰',
      hot: true,
    },
    {
      id: 'd5',
      title: 'کفش کتانی روزمره چرم طبیعی',
      store: 'کفش تهرونی',
      cat: 'fashion',
      tone: 'sage',
      price: 890000,
      old: 1200000,
      percent: 26,
      rating: 4.3,
      ratingCount: 56,
      distance: 800,
      address: 'ستارخان، نبش پاتریس',
      desc: 'چرم گاوی دست‌دوز، زیره‌ی انعطاف‌پذیر.',
      endsIn: '۰۹:۰۰:۰۰',
    },
    {
      id: 'd6',
      title: 'پیتزا دو نفره‌ی ایتالیایی',
      store: 'پیتزا کلاب',
      cat: 'food',
      tone: 'saffron',
      price: 198000,
      old: 320000,
      percent: 38,
      rating: 4.6,
      ratingCount: 620,
      distance: 600,
      address: 'میدان ونک',
      desc: 'خمیر دست‌ساز، سس گوجه‌ی خانگی، موتزارلای تازه.',
      endsIn: '۰۲:۱۵:۳۰',
      hot: true,
    },
    {
      id: 'd7',
      title: 'پک مراقبت پوست سه‌مرحله‌ای',
      store: 'بیوتی لَب',
      cat: 'beauty',
      tone: 'rose',
      price: 420000,
      old: 680000,
      percent: 38,
      rating: 4.4,
      ratingCount: 73,
      distance: 1800,
      address: 'زعفرانیه',
      desc: 'پاک‌کننده، تونر، سرم هیالورونیک؛ برای پوست‌های مختلط.',
      endsIn: '۰۶:۴۵:۱۸',
    },
    {
      id: 'd8',
      title: 'گلدان سرامیکی دست‌ساز',
      store: 'سفالِ خانه',
      cat: 'home',
      tone: 'sage',
      price: 180000,
      old: 260000,
      percent: 30,
      rating: 4.7,
      ratingCount: 34,
      distance: 2200,
      address: 'شهرری، بازار سفالگران',
      desc: 'لعاب آبی سنتی، قابل استفاده برای گیاهان داخل خانه.',
      endsIn: '۲۳:۵۹:۰۰',
    },
  ],
  notifications: [
    { id: 'n1', title: 'پیشنهاد جدید نزدیک تو', body: 'کافه روزگار — صبحانه نصف قیمت', ago: '۱۰ دقیقه پیش', unread: true, icon: 'bolt' },
    { id: 'n2', title: 'قیمت کفش کتانی ارزان‌تر شد', body: '٪۲۶- از ۱٬۲۰۰٬۰۰۰ به ۸۹۰٬۰۰۰', ago: 'یک ساعت پیش', unread: true, icon: 'flame' },
    { id: 'n3', title: 'کیف پول ای‌وای شارژ شد', body: '۱۰۰٬۰۰۰ تومان اضافه شد', ago: 'دیروز', unread: false, icon: 'wallet' },
  ],
};
